###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJIYXJzaCBSYWoifSwiYWxsb3dlZE1ldGhvZHMiOlsiUE9TVCJdLCJpYXQiOjE3MDgzNDQwNjUsImV4cCI6MTcwODM0NDM2NX0.c6RZiZSvqxf8gC-PriMPUSZeifCDrhaDJep9vn98vPk

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJIYXJzaCBSYWoifSwiYWxsb3dlZE1ldGhvZHMiOlsiR0VUIl0sImlhdCI6MTcwODMyODc0Nn0.YQfL2ukKJHquUcgU3Gn-50sqPKrZeoDPfJ5WxJx2raQ"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Harsh Raj"
}

###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiJIYXJzaCBSYWoifSwiYWxsb3dlZE1ldGhvZHMiOlsiR0VUIl0sImlhdCI6MTcwODMyOTg1Nn0.h9umlFxXPLN7aj2FyyP82wMbTy-S0RMULP2b_9roGng"
}