###
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hhc3dpa2EiLCJpYXQiOjE2ODk5NTM5NDEsImV4cCI6MTY4OTk1NDAwMX0.YcSwlgW7pbom2S4cNgp04SNSk_WsIrCymapSOpdqeVs

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2hhc3dpa2EiLCJpYXQiOjE2ODk5NTM5NDF9.Jx_L_X5HNvn_bk4cJOHINkIHI14u36UC67FoTb9dzfo"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username" : "Shaswika"
}

###
DELETE http://localhost:4000/logout

{
    "token" : 
}